### ISSUE TITLE
Cleanup parameter and temporary files

### ISSUE THREAD

**Issue by jensmelinder** [runnholm/CROCOA#7]
When setting Cleanup to False the temp directory is kept (by design). However, the script actually read all (flt) files present in the temp dir to perform the matching which leads to problems in later runs (if temp is not deleted).

Suggestions:
a) make unique names for the temp directory, i.e. 'temp'+date-time or similar
b) leave as is but put in a note in the documentation
c) always delete the temp directory if it exists at the start of a new run.
d) allow the user to set the temp dir name with the Cleanup variable, if that directory already exists, delete it first.

Slight preference for a) on my part.

**Comment by runnholm** [comment]
I added a quick fix to resolve this according to option a)
